stages:
  data_ingestion:
    cmd: python src\pipeline\data_ingestion_pipeline.py
    deps:
    - src\components\data_ingestion.py
    # outs:
    # - artifacts\data_ingestion

  prepare_base_model:
    cmd: python src\pipeline\prepare_base_model_pipeline.py
    deps:
    - src\components\prepare_base_model.py
    # - artifacts\data_ingestion\Chicken-fecal-images
    outs:
    - artifacts\prepare_base_model

  training:
    cmd: python src\pipeline\training_pipeline.py
    deps:
    - artifacts\prepare_base_model\base_model_updated.h5
    - src\components\prepare_callback.py
    - src\components\training.py
    # - artifacts\data_ingestion\Chicken-fecal-images
    outs:
    - artifacts\training\model.h5

  model_evaluation:
    cmd: python src\pipeline\evaluation_pipeline.py
    deps:
    - src\components\model_evaluation.py
    - artifacts\training\model.h5
    # - artifacts\data_ingestion\Chicken-fecal-images
    metrics:
    - scores.json:
        cache: false
